### ISSUE TITLE
Multiple functions

### ISSUE THREAD

**Issue by ccoffman-ebsco** [appleboy/lambda-action#12]
I am creating a repository of multiple lambda functions and wanted a singular deployment action that will loop through them. I don't see this being possible with the current implementation. I would like to be able to supply a list of function names and a collection of zips to be deployed.

Thoughts?

**Comment by fabiofdsantos** [comment]
You just need to duplicate the following instructions:
```
    - name: Deploy function 1
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ env.AWS_REGION }}
        function_name: ${{ env.FUNCTION_X }}
        zip_file: file.zip

    - name: Deploy function 2
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ env.AWS_REGION }}
        function_name: ${{ env.FUNCTION_2 }}
        zip_file: file.zip
```
