### ISSUE TITLE
Modify Lambda Function Timeout

### ISSUE THREAD

**Issue by arsandov** [appleboy/lambda-action#13]
When a new deployment is done to Lambda, the action resets the lambda basic settings to default. Is there a way to define the timeout as a variable or prevent the action from using resetting the lambda function setting to default values?
Added screenshot of default values for Lambda
![image](https://user-images.githubusercontent.com/2084053/96952443-41346e00-14c5-11eb-814e-c8774707408d.png)
Thanks!

**Comment by appleboy** [comment]
I will add some parameter like as

1. memory
2. run time
3. timeout
4. description

Thanks for your feedback

**Comment by arsandov** [comment]
Sounds good. Thank you @appleboy! We will be looking forward for the update.

**Comment by appleboy** [comment]
@arsandov Try to the master branch or [v0.0.5](https://github.com/appleboy/lambda-action/releases/tag/v0.0.5)

```yaml
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: gorush
          zip_file: example/deployment.zip
          memory_size: 128
          timeout: 10
          handler: foobar
```
