### ISSUE TITLE
Please provide ImageUri when updating a function with packageType Image.

### ISSUE THREAD

**Issue by kerim1510** [appleboy/lambda-action#28]
I got the following error:
```
2021/02/23 14:47:09 InvalidParameterValueException InvalidParameterValueException: Please provide ImageUri when updating a function with packageType Image.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "d5747570-f7e0-4637-9e0a-868c82106c61"
  },
  Message_: "Please provide ImageUri when updating a function with packageType Image.",
  Type: "User"
}
```

When using the following params:

```
Run appleboy/lambda-action@v0.1.1
  with:
    aws_access_key_id: ***
    aws_secret_access_key: ***
    aws_region: ***
    function_name: ***
    image_uri: ***
    publish: true
    memory_size: 0
    timeout: 0
  env:
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
```

Any advise?

**Comment by freuk** [comment]
Same issue:
```
    - with:
        function_name: api-server-container
        image_uri: ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/${{secrets.IMAGENAME}}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        publish: 'true'
      uses: appleboy/lambda-action@v0.1.1
      name: Update API-Server Lambda
      id: update-lambda
    name: ecr-publish
```
