### ISSUE TITLE
feature request: specify layers in update-function-configuration

### ISSUE THREAD

**Issue by ryanhuff** [appleboy/lambda-action#29]
I would love to be able to specify layers:
```
      - name: deploy navigate-api-handler
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: my-region
          function_name: my-function-arn
          zip_file: function-code.zip
          layers: layer1-version-arn,layer2-version-arn,layer3-version-arn
```
