### ISSUE TITLE
Syntax for list of layers

### ISSUE THREAD

**Issue by jackgle** [appleboy/lambda-action#39]
Hello, I'm trying to add layers to the lambda configuration, but when I use this syntax:

```
- uses: appleboy/lambda-action@master
  with:
        aws_access_key_id: ...
        ...
        layers: ['arn_1:version', 'arn_2:version']
```

I receive the error `A sequence was not expected` at the `layers` line. What is the correct syntax for a list of layers?

Thanks!
