### ISSUE TITLE
New version is published even if publish: false has been set

### ISSUE THREAD

**Issue by danielkuske** [appleboy/lambda-action#42]
I am trying to not publish a new version. Even after setting the corresponding flag "publish: false" I am still facing the same behaviour as before.

Here is the code snipped I am using, which creates new Versions for every deploy:
```
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          publish: false
          function_name: my-function-name
          zip_file: lambda.zip
```
