### ISSUE TITLE
Cannot use IAM Role to deploy

### ISSUE THREAD

**Issue by bdowne01** [appleboy/lambda-action#44]
If you're assuming roles to deploy your lambdas, which is AWS best practice, this action will not work as it only takes a AWS IAM Key and Secret Key for credentials.   The role parameter is only to set the target lambda's execution role.

Adding an option to assume-role for deploys would be great.

**Comment by elmurci** [comment]
+1

**Comment by sssd-dev** [comment]
+1

**Comment by karl-sprig** [comment]
Does this not work?

https://github.com/aws-actions/configure-aws-credentials

That action takes an ARN and sets the env-vars so other things don't need to do anything out of the normal AWS api sdk behavior of check/user auth in env-vars

**Comment by gegnew** [comment]
_Does_ it work? I have been unable to get it to work using `configure-aws-credentials`.

```
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: deploy to lambda
on: [push]
jobs:
  build:
    name: Build Lambda Functions
    env:
      BUCKET_NAME: s3://org/repo/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build functions
        run: ./install.sh

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::ORG-ID:role/GithubActionsLambdaDeployRole
          role-duration-seconds: 900
          aws-region: us-east-1

      - name: Deploy Lambda to AWS
        # if: github.ref == 'refs/heads/release'
        uses: appleboy/lambda-action@master
        with:
          # gets secrets set in env by `configure-aws-credentials`
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: lambdaFunctionName
          zip_file: build/lambaFunctionName.zip
          dry_run: true
```

and the `GithubActionsLambdaDeployRole` has a policy with [these permissions](https://github.com/appleboy/lambda-action#aws-policy).

But I always get an `UnrecognizedClientException`
