### ISSUE TITLE
ResourceConflictException: … An update is in progress for resource

### ISSUE THREAD

**Issue by aleon68** [appleboy/lambda-action#46]
We have received for all deploys (new and old lambdas) this error, maybe related to this:

https://forums.aws.amazon.com/thread.jspa?threadID=346005

**Comment by gurugutten** [comment]
> We have received for all deploys (new and old lambdas) this error, maybe related to this:
> 
> https://forums.aws.amazon.com/thread.jspa?threadID=346005

We experience the same.

```
 - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: id
          aws_secret_access_key: key
          aws_region: eu-west-1
          runtime: nodejs14.x
          function_name: #LAMBDA#
          zip_file: lambdas/#LAMBDA#/bundle.zip
          publish: true
```


2021/11/23 09:00:17 ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-1:xxxxxxxxxxxxx:function:lambdafunction
```
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: "93137e18-d549-4074-b7da-3c4ef46fae6f"
  },
  Message_: "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-1:xxxxxxxxxxxxx:function:lambdafunction",
  Type: "User"
}
```

**Comment by marchof** [comment]
This is obviously due to the change described here: https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

If you specify multiple properties (like `image_uri` and `memory_size`) the tool probably internally issues multiple subsequent requests which fail due to the new `InProgress` status.

**Comment by aleon68** [comment]
Yes, Understand that, on my YML, I have multiple updates (description,
handler, environments, etc) all of thems was updated without error, but the
process fail updating the zip with code.

I Understand the article, but can see how can Solve the error.

**Comment by aleon68** [comment]
Sorry, I try Say:

I can't see how solve the error

**Comment by merzikain** [comment]
I've been talking with AWS tech support and this is what they have to say:

"I dug into the CloudTrail events for the Lambda service and found that each ‘UpdateFunctionCode’ call that failed with an ‘update in progress’ message was accompanied by a successful ‘UpdateFunctionConfiguration’ call at the same timestamp [1]. Both of these API calls can create the ‘inProgress’ Lambda State [2]. Please verify if the automated update system calls both of these APIs in quick succession. In this case, a loop to check for the ‘inProgress’ state would need to be implemented for the ‘UpdateFunctionCode’ call to allow a delay for the ‘UpdateFunctionConfiguration’ action to complete."

Is that maybe what's causing the issue? If properties being set in the YML are causing the issue it seems like this is a good place to look to resolve it.

**Comment by MauricioAntonioMartinez** [comment]
Have the same issue, watching cloud trail it's trying to create the function besides being already created, and update the code at the same time.

**Comment by Ankit05012019** [comment]
I have the same issue , cloud trail shows `updatefunctionconfiguration` and `updatefunctioncode` both events triggered at the same time.

**Comment by ogohogo** [comment]
same thing here, hopefully this repo is still properly managed. @appleboy @szunami @filipebarros @DmytroSH

**Comment by kevouellet** [comment]
The only way to work around this issue currently is to remove all the properties that cause an UpdateFunctionConfiguration API call to AWS. https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html

In my case, I had to comment out the description field and it went through.

**Comment by jaypeedevlin** [comment]
I noticed there is an open PR on the upstream repo that contains the logic: https://github.com/appleboy/drone-lambda/pull/12, I think if that was merged and this repo pointed to the new version it would be fixed.

**Comment by merzikain** [comment]
> I noticed there is an open PR on the upstream repo that contains the logic: [appleboy/drone-lambda#12](https://github.com/appleboy/drone-lambda/pull/12), I think if that was merged and this repo pointed to the new version it would be fixed.

Can we get some feedback on if this is being handled or if this has been abandoned? Just want to know if I need to just build my own service.

**Comment by tiwarisuraj9** [comment]
I was able fix this from comment https://github.com/claudiajs/claudia/issues/226#issuecomment-973321034

example: 

```
name: deploy to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: gorush
          source: example/index.js
          description: "aws:states:opt-out"

**Comment by exalted** [comment]
According to [this post](https://aws.amazon.com/de/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/) `aws:states:opt-out` shouldn't be working as a workaround anymore (as of "October 01 2021 – End of Delayed Update"). 🤷‍♂️

**Comment by aleon68** [comment]
Right, but is working

**Comment by exalted** [comment]
Well, actually no, my bad: There's an update at the top of that page:

<img width="982" alt="CleanShot 2021-12-09 at 15 47 15@2x" src="https://user-images.githubusercontent.com/314398/145418105-5a758fc8-8e41-4a16-943a-447b7028d3ce.png">

So, apparently, this should've broken as of yesterday… 🙄 Maybe this explains yesterday's AWS outage?! 😛

**Comment by aleon68** [comment]
Again you are right, maybe this explain downtime on services

**Comment by aleon68** [comment]
Maybe the update was done on services, but the problem persists.

I was doing a test right now, performing a deploy with an existent lambda (previously deployed with aws:states:opt-out label), deleting label and redeploy, and failed the deploy. Restoring the label the deployment finish successfully.

I don't understand the AWS logic, but using the label aws:states:opt-out on lambdas can complete deploy.

**Comment by aleon68** [comment]
Starting today, the problem appears again. Before I was solved adding on description of lambda aws:states:opt-out, but now this is not working.
Someone can help me?

**Comment by marcos-pricefy** [comment]
I have de same problem even using "aws:states:opt-out" I have got problems.
Does anyone have any ideas?
This was already updated since when aws recommended it, it was working, but yesterday it didn't!

**Comment by thierrysuzanne-cl** [comment]
Same problem here, would really appreciate a fix soon. We had same error in powershell scripts when calling Publich-LMVersion straight after a call to Update-LMFunctionCode. We fixed it by adding a waiting loop (not shown) in between those calls, with a timeout (not shown), something like:
```
$getFunctionResponse = Get-LMFunction -FunctionName $FunctionName
if ($getFunctionResponse.Configuration.LastUpdateStatus -eq 'Successful') {
    # continue normal execution here
}
```

**Comment by 94929** [comment]
Anyone solved this issue? Adding `description: "aws:states:opt-out"` doesn't work for me unfortuantely.

**Comment by exalted** [comment]
FYI; Since then we've migrated to AWS CLI (i.e. `aws lambda update-function-code ...`)

**Comment by 94929** [comment]
@exalted Thanks for letting me know. So I guess this repository is no longer (actively) maintained then?

**Comment by erikcc02** [comment]
I'm facing this problem in deploy step:

```bash
2023/02/10 14:40:33 ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:***:****:function:account-transfers-lambda
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: "11040c97-d69c-43d3-a19a-b"
  },
  Message_: "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:***:***",
  Type: "User"
}
```
This is my config:

```yaml
 - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: account-transfers-lambda
          zip_file: package/function.zip
          handler: lambda_function.lambda_handler
          runtime: python3.8
```

**Comment by samdelong** [comment]
I wouldn't recommend using this package as it doesn't seem to be maintained anymore. I was able to deploy my go function with the `aws-actions/setup-sam@v1` action.

**Comment by aleon68** [comment]
> I wouldn't recommend using this package as it doesn't seem to be maintained anymore. I was able to deploy my go function with the `aws-actions/setup-sam@v1` action.

How can I apply this action? I could use same yml or need other configuration?
Sorry by ask about that, I'm not expert on deploy with github actions

**Comment by appleboy** [comment]
fix in https://github.com/appleboy/lambda-action/releases/tag/v0.1.6

**Comment by jjlabajo** [comment]
Hello @appleboy , it's still not working on my end.

**Comment by appleboy** [comment]
@jjlabajo Please provide detailed information.

**Comment by johnwmccallum** [comment]
I'm still getting this error:

`2023/04/02 16:48:15 ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:***:741546933029:function:option-pairing
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: "d63709c9-7e47-4733-a817-a36d91b95737"
  },
  Message_: "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:***:741546933029:function:option-pairing",
  Type: "User"
}`

**Comment by appleboy** [comment]
@johnwmccallum Please help to try the following commit sha:

```yaml
appleboy/lambda-action@390dab2546e6c97ca3b94fc5f3863d0e15bec0ee
```

You will see the following log:

![image](https://user-images.githubusercontent.com/21979/229412608-5b6f5083-dbdf-48cb-9d00-94b5e8f4031c.png)

```
2023/04/03 04:16:14 Update function configuration ...
2023/04/03 04:16:15 Current State: Active
2023/04/03 04:16:15 Last Update Status: InProgress
2023/04/03 04:16:15 Last Update Status Reason: The function is being created.
2023/04/03 04:16:15 Last Update Status ReasonCode: Creating
2023/04/03 04:16:15 Waiting Last Update Status to be successful ...
2023/04/03 04:16:40 Update function code ...
2023/04/03 04:16:40 Current State: Active
2023/04/03 04:16:40 Last Update Status: InProgress
2023/04/03 04:16:[40](https://github.com/appleboy/lambda-action/actions/runs/4592683642/jobs/8110202047#step:14:42) Last Update Status Reason: The function is being created.
2023/04/03 04:16:40 Last Update Status ReasonCode: Creating
2023/04/03 04:16:40 Waiting Last Update Status to be successful ...
```

**Comment by appleboy** [comment]
Hi All,

Please help to try the following config:

```yaml
      - name: check max attempts flag
        uses: appleboy/lambda-action@390dab2546e6c97ca3b94fc5f3863d0e15bec0ee
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: gorush
          zip_file: example/deployment.zip
          debug: true
          publish: false
```

## How to resolve the problem

1. Check the Lambda function states before updating the config
2. Check the Lambda function states again before uploading the zip file or source code.

See the reference: https://docs.aws.amazon.com/lambda/latest/dg/functions-states.html

**Comment by appleboy** [comment]
@erikcc02 @94929 @samdelong @exalted @sefasenturk95 @thierrysuzanne-cl  @marcos-pricefy @tiwarisuraj9 @merzikain @jaypeedevlin @kevouellet @ogohogo @Ankit05012019 @gurugutten

Please help to try the test version `appleboy/lambda-action@390dab2546e6c97ca3b94fc5f3863d0e15bec0ee`and @aleon68 has confirmed that 390dab254 fixed the problem in https://github.com/appleboy/lambda-action/issues/58#issuecomment-1493644744

I will bump the new version later.

Thanks.

**Comment by exalted** [comment]
Hey there, I stopped using this action a while ago. Sorry. 🙁

**Comment by appleboy** [comment]
@exalted OK. Thanks. Please accept my apologies for the delay in handling the situation.

**Comment by exalted** [comment]
No worries. I appreciate your humbleness!

**Comment by nex84** [comment]
> 

Hello
Thank you, it seems to have solved the issue for me : 
```
      - name: default deploy
        uses: appleboy/lambda-action@390dab2546e6c97ca3b94fc5f3863d0e15bec0ee # old : appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
          function_name: api-demo
          source: lambda-api-server.py
```

**Comment by appleboy** [comment]
@nex84 Thanks for your help in testing. I will bump the new version later.

**Comment by appleboy** [comment]
Hi All, please use the v0.1.9 version.

```yaml
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
          function_name: api-demo
          source: lambda-api-server.py
```
