### ISSUE TITLE
Env vars? 

### ISSUE THREAD

**Issue by vemundeldegard** [appleboy/lambda-action#5]
Can I add environmental variables to the variables of this action? 

Such as 
```
- with:
   env: 
   - hello: myvar
```

**Comment by appleboy** [comment]
I will take it.

**Comment by misilot** [comment]
Was this ever added?

**Comment by appleboy** [comment]
@misilot @vemundeldegard 

try the following example:

```yaml
      - name: deploy zip
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: gorush
          zip_file: example/deployment.zip
          environment: foo=bar,author=appleboy
          debug: true
```

I will release the new version asap.
