### ISSUE TITLE
Deployment fails on empty "layers" input

### ISSUE THREAD

**Issue by lech-r** [appleboy/lambda-action#55]
According to [AWS Docs](https://docs.amazonaws.cn/en_us/lambda/latest/dg/API_UpdateFunctionConfiguration.html#API_UpdateFunctionConfiguration_RequestSyntax) "layers" input is not required.
This used to work, last time about March 28th (2 days ago).

Fails this morning with this error:
`ValidationException: 1 validation error detected: Value '[]' at 'layers' failed to satisfy constraint`

**Comment by appleboy** [comment]
Please use the stable version

```yaml
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.5
```

I also revert the previous commit.
