### ISSUE TITLE
Passing environment input overwrite existing environment variables

### ISSUE THREAD

**Issue by edixonvargas** [appleboy/lambda-action#66]
When using environment input, the result will be all env variables overwritten with only ASPNETCORE_ENVIRONMENT variable

```
 with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: ${{ secrets.AWS_REGION }}
            function_name: ${{ env.LAMBDA_NAME }}
            image_uri: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            role:  ${{ env.LAMBDA_ROLE }}
            timeout: 30
            environment: ASPNETCORE_ENVIRONMENT=Production
```
