### ISSUE TITLE
InvalidParameterValueException: SubnetIds and SecurityIds must coexist or be both empty list.

### ISSUE THREAD

**Issue by vriabets-blackbird** [appleboy/lambda-action#72]
In description of lambda I'm describing parameter like this 
```
- name: default deploy
  uses: appleboy/lambda-action@v0.1.9
  with:
    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    function_name: func-1
    source: functions/func-1/main
    memory_size: 128
    timeout: 300
    handler: main
    role: "arn:aws:iam::foo:role/func-1-role"
    runtime: go1.x
    subnets: "subnet-123456,subnet-123465,subnet-423156"
    securitygroups: "sg-asdqwf324234"
    environment: ENVIRONMENT=foo
```
And I keep receiving error 
`InvalidParameterValueException InvalidParameterValueException: SubnetIds and SecurityIds must coexist or be both empty list.`
I've tried to find example how to describe the subnets and SG but unfortunately didn't find any.

How to properly provide list of subnets and SG's here?
