### ISSUE TITLE
Add `if: github.ref == 'refs/heads/master'` to example docu

### ISSUE THREAD

**Issue by nomeata** [appleboy/lambda-action#8]
Maybe you assume that people will think about this, but I think it would be nice if the example from the documentation at https://github.com/marketplace/actions/aws-lambda-deploy would only deploy from the `master` branch (I think you usually only ever want to deploy from a specific branch, `master` or `release`)

```
      - name: default deploy
        if: github.ref == 'refs/heads/master'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: gorush
          zip_file: example/deployment.zip
```
