### ISSUE TITLE
MissingEndpoint: 'Endpoint' configuration is required for this service

### ISSUE THREAD

**Issue by lcsvcn** [appleboy/lambda-action#80]
`2024/06/10 19:24:50 MissingEndpoint: 'Endpoint' configuration is required for this service`

```
name: deploy to lambda
on:
  push:
    branches:
      - main
jobs:
  deploy_python:
    name: deploy python lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: install dependencies
        run: pip install -r requirements.txt -t .
      - name: package Python code
        run: zip -r python_deployment.zip .
      - name: deploy Python Lambda function
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: python-microservice-lambda
          zip_file: python_deployment.zip
          runtime: python3.9
```
