### ISSUE TITLE
Lambda architectures is not updated

### ISSUE THREAD

**Issue by MrMarciaOng** [appleboy/lambda-action#84]
Current my lambda function is on x86 and i want to change it to arm64

```
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-southeast-1
          function_name: StageTwilloSMS
          zip_file: bundle.zip
          architectures: arm64
          memory_size: 192
          runtime: nodejs18.x
          timeout: 20
 ```
 
 after deployment, architecture of the lambda function remain unchanged
